version: '3.2'

services:
    gst-ai-object-detection:
      image: hub.foundries.io/${FACTORY}/qimsdk-lmp:latest
      restart: always
      network_mode: "host"
      tty: true
      stop_grace_period: 5s
      command: /opt/gst/gst-ai-object-detection -t 3
      volumes:
        - /opt:/opt
