version: '3.2'

services:
    gst-ai-daisychain-detection-classification:
      image: hub.foundries.io/lmp/qimsdk:v94
      restart: always
      network_mode: "host"
      tty: true
      stop_grace_period: 5s
      command: gst-ai-daisychain-detection-classification --camera
      volumes:
        - /opt:/opt
