version: '3.2'

services:
    gst-ai-monodepth:
      image: hub.foundries.io/${FACTORY}/qimsdk-lmp:latest
      restart: always
      network_mode: "host"
      tty: true
      stop_grace_period: 5s
      # DLC Model
      # command: /opt/gst/gst-ai-monodepth --ml-framework=1 --model=/opt/gst/midasv2.dlc --labels=/opt/gst/monodepth.labels
      # TFlite Model
      command: /opt/gst/gst-ai-monodepth --ml-framework=2 --model=/opt/gst/midasv2.tflite --labels=/opt/gst/monodepth.labels
      volumes:
        - /opt:/opt
