version: '3.2'

services:
    gst-ai-monodepth:
      image: hub.foundries.io/${FACTORY}/qimsdk-lmp:latest
      restart: always
      network_mode: "host"
      tty: true
      stop_grace_period: 5s
      command: /opt/gst/gst-ai-monodepth --config-file /var/sota/compose-apps/gst-ai-monodepth/config.json
      volumes:
        - /opt:/opt
