version: '3.2'

services:
    gst-ai-parallel-inference:
      image: hub.foundries.io/${FACTORY}/qimsdk-lmp:latest
      restart: unless-stopped
      network_mode: "host"
      tty: true
      stop_grace_period: 5s
      command: command: /opt/gst/gst-ai-parallel-inference --config-file /var/sota/compose-apps/gst-ai-parallel-inference/config.json
      volumes:
        - /opt:/opt
