#!/bin/sh -ex

CMAKE_ARGS="-DCMAKE_INSTALL_PREFIX=/apps -DGST_PLUGINS_QTI_OSS_INSTALL_BINDIR=/apps/bin -DGST_PLUGINS_QTI_OSS_INSTALL_CONFIG=/apps/configs -DGST_VERSION_REQUIRED=1"

cd /src/gst-plugins-qti-oss/gst-sample-apps

# The webrtc demo requires the "plugins-bad" package which is a huge install.
# Disable this to keep things small/easy
rm -rf gst-webrtc-sendrecv-example

# These require qmmf-sdk which is also a large/tricky install
rm -rf gst-camera-burst-capture-example gst-camera-metadata-example gst-camera-per-port-example

APPS=$(ls)

# Build the common lib everything needs first
cd gst-sample-apps-utils
cmake ${CMAKE_ARGS}
make install
[ -e /usr/include/gst ] || ln -s /gstreamer-1.0/gst /usr/include/gst
cp /apps/lib/* /usr/local/lib/
cd ..

for app in ${APPS} ; do
	cd ${app}
	# update default path to where we store models
	if [ -f main.c ]; then
		# Replace default path for models, labels, media and configs
		sed -i 's/\/etc\/labels/\/opt\/gst\/labels/' main.c *.json
		sed -i 's/\/etc\/models/\/opt\/gst\/models/' main.c *.json
		sed -i 's/\/etc\/media/\/opt\/gst\/media/' main.c *.json
		sed -i 's/\/etc\/configs/\/opt\/gst\/configs/' main.c *.json
	fi
	cmake ${CMAKE_ARGS}
	make install
	cd ..
done

echo "== Sample apps are ready to be modified under `pwd` by running make under the subdirectories"
