# x-kiosk-imx8-fishtank/docker-compose.yml
version: '3.6'
services:
    x-kiosk-imx8-fishtank:
      image: hub.foundries.io/lmp/x-kiosk-imx8:3bcfc5b-arm64
      restart: always
      tty: true
      command: "--kiosk --no-first-run --incognito https://webglsamples.org/fishtank/fishtank.html"
      read_only: true
      network_mode: "host"
      tmpfs:
      - /run
      - /var/lock
      - /var/log
      - /tmp
      volumes:
      - /run/user/63:/run/user/63
      - /dev/dri:/dev/dri
      - /dev/galcore:/dev/galcore
      device_cgroup_rules:
        - 'c 199:* rmw'
        - 'c 226:* rmw'
