version: '3.2'

services:
    gst-multi-camera-example:
      image: hub.foundries.io/lmp/qimsdk:v94
      restart: always
      network_mode: "host"
      tty: true
      stop_grace_period: 5s
      command: gst-multi-camera-example -o 0
