version: '3.2'

services:
    gst-concurrent-videoplay-composition:
      image: hub.foundries.io/${FACTORY}/qimsdk-lmp:latest
      restart: always
      network_mode: "host"
      tty: true
      stop_grace_period: 5s
      command: /opt/gst-concurrent-videoplay-composition -c 4 -i /opt/beach.mp4 -i /opt/birds.mp4 -i /opt/cloud.mp4 -i /opt/water.mp4
      volumes:
        - /opt:/opt
